# Generated by Django 5.0.6 on 2024-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
