# Generated by Django 5.0.6 on 2024-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='msg_send_count',
            field=models.IntegerField(default=0),
        ),
    ]
