# Generated by Django 5.0.6 on 2024-06-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_privatemessage_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='seen_count',
            field=models.IntegerField(default=0),
        ),
    ]
