# Generated by Django 5.0.6 on 2024-06-24 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_groupmessage_seen_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereadtracking',
            unique_together={('message', 'read_by_user')},
        ),
    ]
