# Generated by Django 5.0.6 on 2024-06-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_remove_group_admins_remove_group_members_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
        migrations.AlterModelTable(
            name='groupmessage',
            table='GroupMessage',
        ),
        migrations.AlterModelTable(
            name='groupuser',
            table='GroupUser',
        ),
        migrations.AlterModelTable(
            name='messagereadby',
            table='MessageReadBy',
        ),
        migrations.AlterModelTable(
            name='privatemessage',
            table='PrivateMessage',
        ),
        migrations.AlterModelTable(
            name='useractivity',
            table='UserActivity',
        ),
    ]
