# Generated by Django 5.0.6 on 2024-06-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_alter_group_table_alter_groupmessage_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
        migrations.AlterModelTable(
            name='groupmessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='messagereadby',
            table=None,
        ),
        migrations.AlterModelTable(
            name='privatemessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='useractivity',
            table=None,
        ),
    ]
