# Generated by Django 5.0.6 on 2024-06-19 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_rename_groupuser_groupmember_alter_groupmember_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'member')},
        ),
    ]
